export const tasks = [
    {
        id: 1,
        title: 'Dê bom dia a alguém na rua',
        skill: 'Extroversão',
        completed: false,
        difficulty: 2,
        usersCompleted: 181,
        rating: 4.8,
        completionRate: 74,
    },
    {
        id: 2,
        title: 'Peça informação para alguém desconhecido',
        skill: 'Oratória',
        completed: false,
        difficulty: 3,
        usersCompleted: 214,
        rating: 4.9,
        completionRate: 81,
    },
    {
        id: 3,
        title: 'Grave um áudio de 1 minuto',
        skill: 'Oratória',
        completed: false,
        difficulty: 4,
        usersCompleted: 163,
        rating: 4.7,
        completionRate: 69,
    },
    {
        id: 4,
        title: 'Encare um desconhecido e dê um sorriso',
        skill: 'Coragem',
        completed: false,
        difficulty: 2,
        usersCompleted: 192,
        rating: 4.6,
        completionRate: 71,
    },
    {
        id: 5,
        title: 'Apresente-se em 30 segundos para um colega',
        skill: 'Confiança',
        completed: false,
        difficulty: 3,
        usersCompleted: 176,
        rating: 4.8,
        completionRate: 77,
    },
    {
        id: 6,
        title: 'Faça um elogio sincero para alguém',
        skill: 'Empatia',
        completed: false,
        difficulty: 2,
        usersCompleted: 205,
        rating: 4.9,
        completionRate: 84,
    },
    {
        id: 7,
        title: 'Conte uma história curta em voz alta',
        skill: 'Oratória',
        completed: false,
        difficulty: 4,
        usersCompleted: 168,
        rating: 4.7,
        completionRate: 73,
    },
    {
        id: 8,
        title: 'Pergunte algo novo em um grupo',
        skill: 'Oratória',
        completed: false,
        difficulty: 3,
        usersCompleted: 187,
        rating: 4.8,
        completionRate: 79,
    },
];
